apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsWeb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsWeb
  template:
    metadata:
      labels:
        app: devopsWeb
    spec:
      containers:
        - name: devopsWeb
          image: prashant4875/devopsWeb:latest
          ports:
            - containerPort: 8080 # Use port 8080
---
apiVersion: v1
kind: Service
metadata:
  name: devopsWeb-service
spec:
  selector:
    app: devopsWeb
  ports:
    - protocol: TCP
      port: 80 # Expose port 80
      targetPort: 8080
  type: LoadBalancer
